name: release

on:
  push:
    tags:
    - 'v[0-9].[0-9].[0-9]*'

jobs:
  release:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pdm-project/setup-pdm@v4
      with:
        cache: true
    - run: pdm install
    - run: pdm run pyinstaller
    - uses: softprops/action-gh-release@v2
      with:
        files: dist/*
